services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql-sql-bsn
    environment:
      MYSQL_DATABASE: book_social_network
      MYSQL_PASSWORD: ${user_password}
      MYSQL_ROOT_PASSWORD: ${user_password}

    volumes:
      - bsn_api_book_db:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - book-social-network
    restart: unless-stopped

  bsn-api:
    container_name: bsn-api-1
    image: bsn/bsn-api-1:1.0.1
    ports:
      - "9000:9000"
    networks:
      - book-social-network
    depends_on:
      - mysql
    restart: unless-stopped

  bsn-ui:
    container_name: bsn-ui-1
    image: bsn/bsn-ui-1:1.0.1
    ports:
      - "9002:80"
    networks:
      - book-social-network
    depends_on:
      - bsn-api
    restart: unless-stopped

networks:
  book-social-network:
    driver: bridge

volumes:
  bsn_api_book_db: