spring:
  datasource:
    url: jdbc:mysql://${mysql_host:localhost}:3306/book_social_network?serverTimezone=UTC&&createDatabaseIfNotExist=true
    username: ${username}
    password: ${user_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: mysql
  mail:
    host: ${host-email}
    port: ${port-email}
    username: ${username-email}
    password: ${password-email}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  security:
    jwt:
      secret-key: ${jwt-secret-key}
      expiration: 86400000
  mail:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      cover-images-output-path: ./uploads
server:
  port: 9000

host-email:
  email: ${user-email}