spring:
  datasource:
    url: jdbc:mysql://${mysql_host:localhost}:3306/book_social_network?serverTimezone=UTC&&createDatabaseIfNotExist=true
    username: ${username}
    password: ${user_pasword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: localhost
    port: 1025
    username: subhi_dajava
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: ${sbn_api_secret_key}
      expiration: 86400000

  mail:
    frontend:
      activation-url: http://${angular-host:localhost}:4200/activate-account
server:
  port: 9000