spring:
  profiles:
    active: dev
  application:
    name: book-network-api

  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/ # This is the base path for all the APIs
